name: SkullDrops
version: 0.1
author: thee
main: me.thee.skulldrops.SkullDrops
commands:
  skull:
    aliases: ['head']
    description: Places <player>'s skull in your inventory
    usage: /<command> <player>
permissions:
  skulldrop.skull:
    description: Allows to youse /skull to receive a skull
    default: op
